# Generated by Django 6.0.3 on 2026-03-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('local', models.TextField()),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCiberseguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('categoria', models.CharField(choices=[('WORKSHOP', 'Workshop'), ('PALESTRA', 'Palestra'), ('TREINAMENTO', 'Treinamento')], default='PALESTRA', max_length=20)),
            ],
        ),
    ]
